### ISSUE TITLE
Add `extends` field to Resource Model

### ISSUE THREAD

**Issue by jmeas** [jmeas/api-pls#142]
This would deep merge the current Resource Model with another file. Supplying `null` to any property would delete it from the previous one (that way, you can, say, omit attributes).

```yaml
extends: '../other-resources/some-other-model.yaml'
pagination: null
meta:
  copyright: 'VARCHAR(30)'
```
